1) Write a python program that finds most frequent element in a given list of numbers (mode)

In [1]:
#random numbers of 30 to 40 from 10 to 100
import random as rand
import numpy as np
import pandas as pd
import statistics

list1 = np.random.randint(1,10,size=15)


d = {}
for i in list1:
    if i not in d:
        d[i] = 0
    else:
        d[i] += 1
print(d)

value = max(zip(d.values(), d.keys()))[1]
print(value, " " ,d[value])

{8: 0, 7: 3, 3: 1, 4: 0, 9: 1, 1: 0, 6: 1, 2: 0, 5: 0}
7   3


2) Care hospital wamts to know the medical speciality visited by the maximum number of patients. Assume that the patient id of the patient along with the medical speciality visited by the patient is stored in a dictionary as follows {"P":"Pediatrics","O":"Orthopedics","E":"ENT"}


Write a function to find the medical specialtoy visited by the maximum number of patients and return the name of the speciality

<br>__Note:__ Assume that there is always only one medical speciality wchich is visited by the maximum number of patients
<br> Perfrom case sensitive string comparisoin wherever necessary
<br> Sample Input : Expected Output:
[101,P,102,O,302,P,305,P]
<br>  [101,O,102,E,302,P,305,P,401,E]

In [24]:
medical_records = {"P":"Pediatrics","O":"Orthopedics","E":"ENT"}
patients = [101,'O',102,'E',302,'P',305,'P',401,'E',403,'E']

d = {}
for i in range(1,len(patients),2):
    if patients[i] not in d:
        d[patients[i]] = 0
    else:
        d[patients[i]] += 1
m = max(list(d.values()))
id = {id for id in d if d[id] == m}
s = " ".join(id)
print(s)
print("The speciality is: " , medical_records[s])

E
The speciality is:  ENT


<br>3) Write python fn sms_encoding() which accepts a sentence and cnverts it into an abbreviated sentence to be sent as SMS and returns the abbreviated sentence

<br> Rules are as follows:
<br> a. Spaces are to be returned as is
b.Eah word should be encoded seperately

If a word has only vowels then retain the word as is
If a word has a consonant (at least1) then retain only those consonants

__Note:__ Assume that the sentence would begin with a word and there will be only a single space between the words.

        Sample Input: Exp o/p:
        I love Python    I lv Pythn
        I will not repeat mistakes  I will nt rpt mstks

In [31]:
s = input("Enter the input to perfrom operations")
vowels = ["a","e","i","o","u","A","E","I","O","U"]

vowel , consonants = "",""
ans = ""
list1 = s.split(" ")
for i in list1:
    for j in i:
        if vowels.count(j) >= 1:
            vowel += j
        else:
            consonants += j
        
    if len(consonants) == 0:
            ans += vowel
    else:
            ans += consonants
    
    vowel , consonants = "",""
    ans += " "
print(ans)

Enter the input to perfrom operationsI love apple
I lv ppl 


In [5]:
list = [1,3,4,5,6,7,8]
x = [x for x in list if x == 45]
print(x)

[]


4) Write a python program that accepts a text and displays a string which contains the word with the largest frequency in the text and the frequency itself seperated by a space
<br> __Rules__:
        <br> The word should have the largest frequency
        <br> In case multiple words have the same frequency, then choose the word that has the maximum length

<br><br> __Assumptions__:
        <br> The text has no special characters other than space
        <br> The text would begin with a word and there wll be only a single space between the words.
<br> Input and Output:
<br> "Work like you do not need money love like you have never been hurt"
   like 2
   "Courage is not the absence of fear but rather than the judgement that something else is more important than fear"

In [8]:
s = input("Enter the input to perform checks")
string = ''.join(i for i in s if i.isalnum() or i == " ")

print(string)
list1 = string.split(" ")
d = {}
for i in list1:
    if i not in d:
        d[i] = 0
    else:
        d[i] += 1
m = max(list(d.values()))
listing = {id for id in d if d[id] == m}
print(listing)
if len(listing) == 1:
    string3 = " ".join(listing)
else:
    max(list(string3))

print(string3, " ", m)



Enter the input to perform checksWork like you do not need money love like you have never been hurt like
Work like you do not need money love like you have never been hurt like
{'like'}
like   2


5) Write a python function, find_pairs_of_numbers() which accepts a list of positive integers with no repetation and return the count of pairs of numbers in the list that adds up to n. The function  should return 0, if no such pairs are found in the list. 

Sample Input ---> Sample Output:
   <br>[1, 2, 7, 4, 5, 6, 0, 3] , 6 ----> 3
   <br> [3, 4, 1, 8, 5, 9, 0, 6] , 9 ---> 4

In [25]:
import numpy as np
import random as rand

def find_pairs_of_numbers(list1,target):
    list1.sort()
    count = 0
    l = []
    for i in range(len(list1)-1):
        if list1[i] + list1[i+1] == target:
            count += 1
            l.append(list1[i])
            l.append(list1[i+1])
            #l.append([])
    if count >= 1:
        print(l)
        return count
    else:
        return 0
rand.seed(10)
list1 = np.random.randint(1,15,size=20)
print(list1)
target = 11
ans = find_pairs_of_numbers(list1, target)
print(ans)

[ 2 11  5  8 12 12  8  3  2 10 11  7  7  6  9  4  9  2  4  8]
[5, 6]
1


##### Random package notes:
seed - get same output always
functions like seed(), random(), randint(1,10), randrange(1,10,2)

In [8]:
import numpy as np
print(np.random.randint(1,10,size=10))
print(np.random.choice([1,3,5], 2))
print(np.random.choice([1,3,5], 2, False))

[4 1 8 3 7 4 8 8 5 8]
[5 1]
[3 1]


In [9]:
np.random.seed(10)


### List Comprehension programs:
1) Convert the following logic of list normalization into list comprehension
    <br>nums_list= [6,4,2,8,9,10,3,2,1,3]
    <br>total = float(sum(nums_list))
    <br>for i in range(len(nums_list)):
        <br>           nums_list[i] = nums_list[i]/float(total)
 
2) Convert the following logic of zero-matrix creation into list comprehension:
        <br>zeromatrix = [ ]
         <br>for i in range(10):
         <br>matrix.append([0]*10)
     
3) By using list comprehension, write a program for the following:
        <br>print the list after removing numbers which are divisible by 3 and 5 in [5,10,40,7,53,31,12,10]
        <br> print the list after removing the 0th, 2nd, 4th , 6th numbers in [5,10,40,7,53,31,12,101]
        <br> generate a 3 * 4 2D-list whose elements are initialized to 0
        <br> generate a 2* 3* 5 3D-list whose each elements are initialized to 0

1) Convert the following logic of list normalization into list comprehension
nums_list= [6,4,2,8,9,10,3,2,1,3]
total = float(sum(nums_list))
for i in range(len(nums_list)):
nums_list[i] = nums_list[i]/float(total)

In [39]:

#1 Program of list comprehension:
list1 = np.random.randint(1,10,size=10)
total = float(sum(list1))
ans = [list1[i]/float(total) for i in range(len(list1))]
print(ans)

[0.1509433962264151, 0.1509433962264151, 0.1509433962264151, 0.03773584905660377, 0.1320754716981132, 0.07547169811320754, 0.07547169811320754, 0.018867924528301886, 0.1320754716981132, 0.07547169811320754]


2) Convert the following logic of zero-matrix creation into list comprehension:
zeromatrix = []
for i in range(10):
matrix.append([0]*10)

In [54]:
list1 = []
list1 = [[0 for j in range(10)] for i in range(10)] 
print(list1)

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]


3) By using list comprehension, write a program for the following:
print the list after removing numbers which are divisible by 3 and 5 in [5,10,40,7,53,31,12,10]
print the list after removing the 0th, 2nd, 4th , 6th numbers in [5,10,40,7,53,31,12,101]
generate a 3 * 4 2D-list whose elements are initialized to 0
generate a 2* 3* 5 3D-list whose each elements are initialized to 0

In [62]:
list1 = np.random.randint(5,100,size=10)
print(list1)
x  = [i for i in list1 if i%5!=0 and i&3!=0]
print(x)

lsit1 = [1,2,3,4,5,6,7,8,9,10]
x = [list1[i] for i in range(len(list1)) if i not in (0,2,4,6)]
print(x)

x = [[0 for j in range(3)] for i in range(4)]
print(x)


x = [[0 for j in range(3)] for i in range(4)]
print(x)

[65 45  5 11 87 98 19 14 42 10]
[11, 87, 98, 19, 14, 42]
[45, 11, 98, 14, 42, 10]
[[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]]
[[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]]


### Dictionary programs

1) Do the following:
    <br> .Create a following with a day of week as key and number of letters as value
    <br> .Loop through the created dictioanry, and print the day and number of letters for each entry on a seperate line
    <br> .Loop through the created dictionary, and print the day and number of letters for each entry on a seperate line, but only for days with more than 6 letters


2) Write the python code that prints the total amount of animals contained in this strange zoo given the following dictionary that stores the quantities of each type of animals
    <br> animals = {"dog" : 9, "cat":4, "frog":2, "bear":4, "whale":10}

3) Define a function which can generate a dictionary where the keys are numbers between 1 and 20(both included) and the values are sqaure of keys. The function should just print the keys only.


In [71]:
days = ['Sunday','Monday', 'Tuesday', 'Wednesday', 'Thursday','Friday', 'Saturday']

d= {}
for i in days:
    if i not in d:
        d[i] = len(i)
    else:
        d[i] = len(i)
print(d)


for i in d.keys():
    print(i, ' ',d[i])

print()
for i in d.keys():
    if d[i] > 6:
        print(i, ' ',d[i])
    

{'Sunday': 6, 'Monday': 6, 'Tuesday': 7, 'Wednesday': 9, 'Thursday': 8, 'Friday': 6, 'Saturday': 8}
Sunday   6
Monday   6
Tuesday   7
Wednesday   9
Thursday   8
Friday   6
Saturday   8

Tuesday   7
Wednesday   9
Thursday   8
Saturday   8


In [64]:
animals = {"dog" : 9, "cat":4, "frog":2, "bear":4, "whale":10}
print('The sum is',sum(list(animals.values())))

The sum is 29


In [75]:
def generate():
    d=dict()
    for x in range(1,21):
        d[x]=x**2
    
    print(d.keys())
generate()

dict_keys([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
